### PR TITLE
Added handling of 2 rest env vars for MirrorMaker2

### PR DESCRIPTION
**Pull request by Kuvesz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
Handling of 2 env vars that we use for distributed MM2.

### Why?
We need to handle these 2 env vars somehow for MirrorMaker2 and this seems like an easy and kinda clean solution to do so.

### Checklist

- [X] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### CODE REVIEW

**Review by pregnor — APPROVED** [review]
Make sure to manually test this because I wouldn't put my life on this and don't have enough time to look into the dicy parts.

**Comment by Kuvesz** [comment]
> Make sure to manually test this because I wouldn't put my life on this and don't have enough time to look into the dicy parts.

Yeah, this works in k8s if we use `args` instead of `command`, which is a bit weird. If we use `command` the entrypoint gets overwritten it seems.

**Review by pregnor — CHANGES_REQUESTED** [review]
Let's have a discussion offline about this.

**Comment by Kuvesz** [comment]
Closing this as this won't work as I expected and it's not the cleanest anyway to do this.

**Pull request closed without merging**
